/** Port of bdcat getBirthPlacefromIc — IC digits 7–8 encode birth state/country. */
const BIRTH_PLACES: Record<string, string> = {
  "00": "—",
  "01": "Johor",
  "02": "Kedah",
  "03": "Kelantan",
  "04": "Melaka",
  "05": "Negeri Sembilan",
  "06": "Pahang",
  "07": "Pulau Pinang",
  "08": "Perak",
  "09": "Perlis",
  "10": "Selangor",
  "11": "Terengganu",
  "12": "Sabah",
  "13": "Sarawak",
  "14": "Kuala Lumpur",
  "15": "Labuan",
  "16": "Putrajaya",
  "17": "—",
  "18": "—",
  "19": "—",
  "20": "—",
  "21": "Johor",
  "22": "Johor",
  "23": "Johor",
  "24": "Johor",
  "25": "Kedah",
  "26": "Kedah",
  "27": "Kedah",
  "28": "Kelantan",
  "29": "Kelantan",
  "30": "Melaka",
  "31": "Negeri Sembilan",
  "32": "Pahang",
  "33": "Pahang",
  "34": "Penang",
  "35": "Penang",
  "36": "Perak",
  "37": "Perak",
  "38": "Perak",
  "39": "Perak",
  "40": "Perlis",
  "41": "Selangor",
  "42": "Selangor",
  "43": "Selangor",
  "44": "Selangor",
  "45": "Terengganu",
  "46": "Terengganu",
  "47": "Sabah",
  "48": "Sabah",
  "49": "Sabah",
  "50": "Sarawak",
  "51": "Sarawak",
  "52": "Sarawak",
  "53": "Sarawak",
  "54": "Kuala Lumpur",
  "55": "Kuala Lumpur",
  "56": "Kuala Lumpur",
  "57": "Kuala Lumpur",
  "58": "Labuan",
  "59": "Negeri Sembilan",
  "60": "Brunei",
  "61": "Indonesia",
  "62": "Cambodia / Democratic Kampuchea / Kampuchea",
  "63": "Laos",
  "64": "Myanmar",
  "65": "Philippines",
  "66": "Singapore",
  "67": "Thailand",
  "68": "Vietnam",
  "69": "—",
  "70": "—",
  "71": "Outside Malaysia",
  "72": "Outside Malaysia",
  "73": "—",
  "74": "China",
  "75": "India",
  "76": "Pakistan",
  "77": "Saudi Arabia",
  "78": "Sri Lanka",
  "79": "Bangladesh",
  "80": "—",
  "81": "—",
  "82": "Unknown state",
  "83": "Asia-Pacific",
  "84": "South America",
  "85": "Africa",
  "86": "Europe",
  "87": "Britain / Great Britain / Ireland",
  "88": "Middle East",
  "89": "Far East",
  "90": "Caribbean",
  "91": "North America",
  "92": "Soviet Union / USSR",
  "93": "Unspecified",
  "94": "—",
  "95": "—",
  "96": "—",
  "97": "—",
  "98": "Stateless / Stateless Person Article 1/1954",
  "99": "Unspecified",
};

export function getBirthPlaceFromIc(ic: string): string {
  if (ic.length < 8) return "Invalid IC";
  const code = ic.slice(6, 8);
  return BIRTH_PLACES[code] ?? "Unknown";
}
